import { rgba, invert, readableColor, lighten } from "polished";
import cartographer from "../bgImages/cartographer.png";
import starWarsBgImage from "../bgImages/darkness.png";
import totallyNinetiesBgImage from "../bgImages/bgplaystation.gif";
// ** bgColor is first color;
// ** fontColorSecondary;
// const fontColor = readableColor("#cc208e");
// const fontColorSecondary = fontColor;
const mainFont = `"aktiv-grotesk", -apple-system, BlinkMacSystemFont, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif`;
const mainFontTertiary = `"aktiv-grotesk-condensed", -apple-system, BlinkMacSystemFont, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif`;
const mainFontSecondary = `"aktiv-grotesk-extended", -apple-system, BlinkMacSystemFont, Oxygen, Ubuntu, Cantarell, "Open Sans", "Helvetica Neue", sans-serif`;
const bgColor = "#cc208e";

const courierNewFont = `Courier New", Courier, monospace`;
const lucidaConsoleFont = `"Lucida Console", Monaco, monospace`;
const timesNewRomanFont = `"Times New Roman", Times, serif`;
const comicSansFont = `"Comic Sans","Comic Sans MS","Chalkboard","ChalkboardSE-Regular","Marker Felt","Purisa","URW Chancery L",cursive,sans-serif`;
// const bgColorSecondary = "#6713d2";
const gradientValues = `#cc208e 0%, #6713d2 100%`;

const defaultBaseValues = {
	bgColor,
	gradientValues
};

export const themeMaker = (theme = defaultBaseValues) => {
	const { bgColor, gradientValues } = theme;
	const fontColor = readableColor(bgColor);
	return {
		appBg: `linear-gradient(to right, ${gradientValues})`,
		appBgAnimation: `linear-gradient(-45deg, ${gradientValues})`,
		appBgColor: `transparent`,
		appBgMobile: `linear-gradient(to bottom, ${gradientValues})`,
		appfontFamily: `${mainFont}`,
		appfontFamilySecondary: `${mainFontSecondary}`,
		appfontFamilyTertiary: `${mainFontTertiary}`,
		bgColor: `${bgColor}`,
		bgColorContent: `${rgba(fontColor, 0.2)}`,
		bgColorOverlay: `${rgba(readableColor(fontColor), 0.2)}`,
		bgColorSecondary: `${bgColor}`,
		borderThin: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBackground: `none`,
		buttonBackgroundHoverFocus: `transparent`,
		buttonBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBorderFocus: `1px solid ${fontColor}`,
		buttonBorderActive: `2px solid ${fontColor}`,
		buttonColor: `${rgba(fontColor, 1)}`,
		buttonColorHoverFocus: `${fontColor}`,
		buttonFontWeight: `700`,
		buttonLineHeight: ` 1.2`,
		buttonSpanDisplay: `block`,
		buttonTextTransform: `uppercase`,
		colorLight: `${lighten(0.42, fontColor)}`,
		colorSlightOpacity: `${rgba(fontColor, 0.56)}`,
		CTAColor: `${rgba(fontColor, 1)}`,
		CTAColorSecondary: `${rgba(fontColor, 1)}`,
		CTAUnderline: `none`,
		fontColor: `${fontColor}`,
		fontColorOpposite: `${readableColor(fontColor)}`,
		fontColorSecondary: `${fontColor}`,
		fontSelection: `${invert(fontColor)}`,
		fullScreenHoldBg: `${invert(bgColor)}`,
		logoBgColor: `${rgba(fontColor, 1)}`,
		logoBgHoverColor: `${fontColor}`,
		logoBorderBottom: `1px solid ${rgba(fontColor, 1)}`,
		logoBorderRadius: `0`,
		logoInnerFillColor: `${fontColor}`,
		logoInnerFillColorHoverFocus: `${fontColor}`,
		logoOuterFillColor: `${fontColor}`,
		modalFullScreenBg: `linear-gradient(to right, ${gradientValues})`,
		modalFullScreenBgColor: `transparent`,
		modalFullScreenBgMobile: `linear-gradient(to bottom, ${gradientValues})`,
		navBarBg: "transparent",
		navBarBgComplement: `${bgColor}`,
		navBarBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		navBarButtonColor: `${fontColor}`,
		navBarButtonActive: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryHoverText: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryText: `${rgba(fontColor, 1)}`,
		navBarHoverFocus: `${rgba(fontColor, 0.55)}`,
		navBarHoverFocusAction: "none",
		sliderArrow: `${fontColor}`,
		sliderArrowActive: `${fontColor}`,
		sliderArrowOpacity: "1",
		sliderArrowSecondary: `${fontColor}`,
		sliderBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleActive: `${fontColor}`,
		sliderCircleBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleBorder: `${rgba(fontColor, 0.2)}`,
		sliderCircleHoverFocus: `${rgba(fontColor, 0.2)}`,
		sliderCircleOpacity: `1`,
		sliderLine: `linear-gradient(to right, transparent 50%, ${fontColor} 50%)`,
		sliderLinePortrait: `linear-gradient(to bottom, transparent 50%, ${fontColor} 50%)`,
		tabHeadingsBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		tabHeadingsBorderActive: `0`,
		tabHeadingsBorderBottomActive: `2px solid ${fontColor}`,
		tabHeadingsBorderRadius: `0`,
		tabHeadingsColor: `${rgba(fontColor, 1)}`,
		tabHeadingsColorActive: `${fontColor}`,
		tabHeadingsColorHoverFocus: `${fontColor}`,
		tabHeadingsJustifyContent: `space-between`
	};
};

const bgImageColor = `#252525`;
const bgImage = `${cartographer}`;
const defaultBgImageValues = {
	bgColor: bgImageColor,
	bgImage
};

export const themeBgMaker = (theme = defaultBgImageValues) => {
	const { bgColor, bgImage } = theme;
	const fontColor = readableColor(bgColor);
	return {
		appBg: `url(${bgImage})`,
		appBgAnimation: `${bgColor}`,
		appBgColor: `${bgColor}`,
		appBgMobile: `url(${bgImage})`,
		appfontFamily: `${mainFont}`,
		appfontFamilySecondary: `${mainFontSecondary}`,
		appfontFamilyTertiary: `${mainFontTertiary}`,
		bgColor: `${bgColor}`,
		bgColorContent: `${rgba(fontColor, 0.2)}`,
		bgColorOverlay: `${rgba(readableColor(fontColor), 0.19)}`,
		bgColorSecondary: `${bgColor}`,
		borderThin: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBackground: `none`,
		buttonBackgroundHoverFocus: `transparent`,
		buttonBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBorderFocus: `1px solid ${fontColor}`,
		buttonBorderActive: `2px solid ${fontColor}`,
		buttonColor: `${rgba(fontColor, 1)}`,
		buttonColorHoverFocus: `${fontColor}`,
		buttonFontWeight: `700`,
		buttonLineHeight: ` 1.2`,
		buttonSpanDisplay: `block`,
		buttonTextTransform: `uppercase`,
		colorLight: `${lighten(0.42, fontColor)}`,
		colorSlightOpacity: `${rgba(fontColor, 0.56)}`,
		CTAColor: `${rgba(fontColor, 1)}`,
		CTAColorSecondary: `${rgba(fontColor, 1)}`,
		CTAUnderline: `none`,
		fontColor: `${fontColor}`,
		fontColorOpposite: `${readableColor(fontColor)}`,
		fontColorSecondary: `${fontColor}`,
		fontSelection: `${invert(fontColor)}`,
		fullScreenHoldBg: ` linear-gradient( ${invert(bgColor)}, ${invert(
			bgColor
		)})`,
		logoBgColor: `${rgba(fontColor, 1)}`,
		logoBgHoverColor: `${fontColor}`,
		logoBorderBottom: `1px solid ${rgba(fontColor, 1)}`,
		logoBorderRadius: `0`,
		logoInnerFillColor: `${fontColor}`,
		logoInnerFillColorHoverFocus: `${fontColor}`,
		logoOuterFillColor: `${fontColor}`,
		modalFullScreenBg: `${bgColor}`,
		modalFullScreenBgColor: `transparent`,
		modalFullScreenBgMobile: `${bgColor}`,
		navBarBg: "transparent",
		navBarBgComplement: `${bgColor}`,
		navBarBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		navBarButtonColor: `${fontColor}`,
		navBarButtonActive: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryHoverText: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryText: `${rgba(fontColor, 1)}`,
		navBarHoverFocus: `${rgba(fontColor, 0.55)}`,
		navBarHoverFocusAction: "none",
		sliderArrow: `${fontColor}`,
		sliderArrowActive: `${fontColor}`,
		sliderArrowOpacity: "1",
		sliderArrowSecondary: `${fontColor}`,
		sliderBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleActive: `${fontColor}`,
		sliderCircleBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleBorder: `${rgba(fontColor, 0.2)}`,
		sliderCircleHoverFocus: `${rgba(fontColor, 0.2)}`,
		sliderCircleOpacity: `1`,
		sliderLine: `linear-gradient(to right, transparent 50%, ${fontColor} 50%)`,
		sliderLinePortrait: `linear-gradient(to bottom, transparent 50%, ${fontColor} 50%)`,
		tabHeadingsBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		tabHeadingsBorderActive: `0`,
		tabHeadingsBorderBottomActive: `2px solid ${fontColor}`,
		tabHeadingsBorderRadius: `0`,
		tabHeadingsColor: `${rgba(fontColor, 1)}`,
		tabHeadingsColorActive: `${fontColor}`,
		tabHeadingsColorHoverFocus: `${fontColor}`,
		tabHeadingsJustifyContent: `space-between`
	};
};

export const themeColorMaker = (hexColor = "FFFFFF") => {
	// const values = theme.split("-");
	// const bgColor = `#${values[1]}`;
	// const fontColor = `#${values[2]}`;
	const bgColor = `#${hexColor}`;
	const fontColor = `${readableColor(bgColor)}`;
	return {
		appBg: `${bgColor}`,
		appBgAnimation: `${bgColor}`,
		appBgColor: `${bgColor}`,
		appBgMobile: `${bgColor}`,
		appfontFamily: `${mainFont}`,
		appfontFamilySecondary: `${mainFontSecondary}`,
		appfontFamilyTertiary: `${mainFontTertiary}`,
		bgColor: `${bgColor}`,
		bgColorContent: `${rgba(fontColor, 0.2)}`,
		bgColorOverlay: `transparent`,
		bgColorSecondary: `${bgColor}`,
		borderThin: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBackground: `none`,
		buttonBackgroundHoverFocus: `transparent`,
		buttonBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBorderFocus: `1px solid ${fontColor}`,
		buttonBorderActive: `2px solid ${fontColor}`,
		buttonColor: `${rgba(fontColor, 1)}`,
		buttonColorHoverFocus: `${fontColor}`,
		buttonFontWeight: `700`,
		buttonLineHeight: ` 1.2`,
		buttonSpanDisplay: `block`,
		buttonTextTransform: `uppercase`,
		colorLight: `${lighten(0.42, fontColor)}`,
		colorSlightOpacity: `${rgba(fontColor, 0.56)}`,
		CTAColor: `${rgba(fontColor, 1)}`,
		CTAColorSecondary: `${rgba(fontColor, 1)}`,
		CTAUnderline: `none`,
		fontColor: `${fontColor}`,
		fontColorOpposite: `${readableColor(fontColor)}`,
		fontColorSecondary: `${fontColor}`,
		fontSelection: `${invert(fontColor)}`,
		fullScreenHoldBg: ` linear-gradient( ${invert(bgColor)}, ${invert(
			bgColor
		)})`,
		logoBgColor: `${rgba(fontColor, 1)}`,
		logoBgHoverColor: `${fontColor}`,
		logoBorderBottom: `1px solid ${rgba(fontColor, 1)}`,
		logoBorderRadius: `0`,
		logoInnerFillColor: `${fontColor}`,
		logoInnerFillColorHoverFocus: `${fontColor}`,
		logoOuterFillColor: `${fontColor}`,
		modalFullScreenBg: `${bgColor}`,
		modalFullScreenBgColor: `transparent`,
		modalFullScreenBgMobile: `${bgColor}`,
		navBarBg: "transparent",
		navBarBgComplement: `${bgColor}`,
		navBarBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		navBarButtonColor: `${fontColor}`,
		navBarButtonActive: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryHoverText: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryText: `${rgba(fontColor, 1)}`,
		navBarHoverFocus: `${rgba(fontColor, 0.55)}`,
		navBarHoverFocusAction: "none",
		sliderArrow: `${fontColor}`,
		sliderArrowActive: `${fontColor}`,
		sliderArrowOpacity: "1",
		sliderArrowSecondary: `${fontColor}`,
		sliderBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleActive: `${fontColor}`,
		sliderCircleBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleBorder: `${rgba(fontColor, 0.2)}`,
		sliderCircleHoverFocus: `${rgba(fontColor, 0.2)}`,
		sliderCircleOpacity: `1`,
		sliderLine: `linear-gradient(to right, transparent 50%, ${fontColor} 50%)`,
		sliderLinePortrait: `linear-gradient(to bottom, transparent 50%, ${fontColor} 50%)`,
		tabHeadingsBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		tabHeadingsBorderActive: `0`,
		tabHeadingsBorderBottomActive: `2px solid ${fontColor}`,
		tabHeadingsBorderRadius: `0`,
		tabHeadingsColor: `${rgba(fontColor, 1)}`,
		tabHeadingsColorActive: `${fontColor}`,
		tabHeadingsColorHoverFocus: `${fontColor}`,
		tabHeadingsJustifyContent: `space-between`
	};
};

export const matrixTheme = () => {
	const bgColor = "#252525";
	const fontColor = "#ffffff";
	return {
		appBg: `none`,
		appBgAnimation: `${bgColor}`,
		appBgColor: `${bgColor}`,
		appBgMobile: `none`,
		appfontFamily: `${mainFont}`,
		appfontFamilySecondary: `${mainFontSecondary}`,
		appfontFamilyTertiary: `${mainFontTertiary}`,
		bgColor: `${bgColor}`,
		bgColorContent: `${rgba(fontColor, 0.2)}`,
		bgColorOverlay: `${rgba(readableColor(fontColor), 0.19)}`,
		bgColorSecondary: `${bgColor}`,
		borderThin: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBackground: `none`,
		buttonBackgroundHoverFocus: `transparent`,
		buttonBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBorderFocus: `1px solid ${fontColor}`,
		buttonBorderActive: `2px solid ${fontColor}`,
		buttonColor: `${rgba(fontColor, 1)}`,
		buttonColorHoverFocus: `${fontColor}`,
		buttonFontWeight: `700`,
		buttonLineHeight: ` 1.2`,
		buttonSpanDisplay: `block`,
		buttonTextTransform: `uppercase`,
		colorLight: `${lighten(0.42, fontColor)}`,
		colorSlightOpacity: `${rgba(fontColor, 0.56)}`,
		CTAColor: `${rgba(fontColor, 1)}`,
		CTAColorSecondary: `${rgba(fontColor, 1)}`,
		CTAUnderline: `none`,
		fontColor: `${fontColor}`,
		fontColorOpposite: `${readableColor(fontColor)}`,
		fontColorSecondary: `${fontColor}`,
		fontSelection: `${invert(fontColor)}`,
		fullScreenHoldBg: `${invert(bgColor)}`,
		logoBgColor: `${rgba(fontColor, 1)}`,
		logoBgHoverColor: `${fontColor}`,
		logoBorderBottom: `1px solid ${rgba(fontColor, 1)}`,
		logoBorderRadius: `0`,
		logoInnerFillColor: `${fontColor}`,
		logoInnerFillColorHoverFocus: `${fontColor}`,
		logoOuterFillColor: `${fontColor}`,
		modalFullScreenBg: `${bgColor}`,
		modalFullScreenBgColor: `transparent`,
		modalFullScreenBgMobile: `${bgColor}`,
		navBarBg: "transparent",
		navBarBgComplement: `${bgColor}`,
		navBarBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		navBarButtonColor: `${fontColor}`,
		navBarButtonActive: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryHoverText: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryText: `${rgba(fontColor, 1)}`,
		navBarHoverFocus: `${rgba(fontColor, 0.55)}`,
		navBarHoverFocusAction: "none",
		sliderArrow: `${fontColor}`,
		sliderArrowActive: `${fontColor}`,
		sliderArrowOpacity: "1",
		sliderArrowSecondary: `${fontColor}`,
		sliderBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleActive: `${fontColor}`,
		sliderCircleBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleBorder: `${rgba(fontColor, 0.2)}`,
		sliderCircleHoverFocus: `${rgba(fontColor, 0.2)}`,
		sliderCircleOpacity: `1`,
		sliderLine: `linear-gradient(to right, transparent 50%, ${fontColor} 50%)`,
		sliderLinePortrait: `linear-gradient(to bottom, transparent 50%, ${fontColor} 50%)`,
		tabHeadingsBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		tabHeadingsBorderActive: `0`,
		tabHeadingsBorderBottomActive: `2px solid ${fontColor}`,
		tabHeadingsBorderRadius: `0`,
		tabHeadingsColor: `${rgba(fontColor, 1)}`,
		tabHeadingsColorActive: `${fontColor}`,
		tabHeadingsColorHoverFocus: `${fontColor}`,
		tabHeadingsJustifyContent: `space-between`
	};
};

export const themeStarWars = () => {
	const bgColor = "#000000";
	const fontColor = "#ffd54e";
	const starWarsBlue = "#4bd5ee";
	return {
		appBg: `url(${starWarsBgImage})`,
		appBgAnimation: `${bgColor}`,
		appBgColor: `${bgColor}`,
		appBgMobile: `url(${starWarsBgImage})`,
		appfontFamily: `${mainFont}`,
		appfontFamilySecondary: `${mainFontSecondary}`,
		appfontFamilyTertiary: `${mainFontTertiary}`,
		bgColor: `${bgColor}`,
		bgColorContent: `${rgba(fontColor, 0.2)}`,
		bgColorOverlay: `${rgba(readableColor(fontColor), 0.19)}`,
		bgColorSecondary: `${bgColor}`,
		borderThin: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBackground: `none`,
		buttonBackgroundHoverFocus: `transparent`,
		buttonBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		buttonBorderFocus: `1px solid ${fontColor}`,
		buttonBorderActive: `2px solid ${fontColor}`,
		buttonColor: `${rgba(fontColor, 1)}`,
		buttonColorHoverFocus: `${fontColor}`,
		buttonFontWeight: `700`,
		buttonLineHeight: ` 1.2`,
		buttonSpanDisplay: `block`,
		buttonTextTransform: `uppercase`,
		colorLight: `${lighten(0.42, fontColor)}`,
		colorSlightOpacity: `${rgba(fontColor, 0.56)}`,
		CTAColor: `${rgba(starWarsBlue, 1)}`,
		CTAColorSecondary: `${rgba(starWarsBlue, 1)}`,
		CTAUnderline: `none`,
		fontColor: `${fontColor}`,
		fontColorOpposite: `${readableColor(fontColor)}`,
		fontColorSecondary: `${fontColor}`,
		fontSelection: `${invert(fontColor)}`,
		fullScreenHoldBg: ` linear-gradient( ${invert(bgColor)}, ${invert(
			bgColor
		)})`,
		logoBgColor: `${rgba(fontColor, 1)}`,
		logoBgHoverColor: `${fontColor}`,
		logoBorderBottom: `1px solid ${rgba(fontColor, 1)}`,
		logoBorderRadius: `0`,
		logoInnerFillColor: `${starWarsBlue}`,
		logoInnerFillColorHoverFocus: `${starWarsBlue}`,
		logoOuterFillColor: `${starWarsBlue}`,
		modalFullScreenBg: `${bgColor}`,
		modalFullScreenBgColor: `transparent`,
		modalFullScreenBgMobile: `${bgColor}`,
		navBarBg: "transparent",
		navBarBgComplement: `${bgColor}`,
		navBarBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		navBarButtonColor: `${starWarsBlue}`,
		navBarButtonActive: `${rgba(starWarsBlue, 0.55)}`,
		navBarButtonComplementaryHoverText: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryText: `${rgba(fontColor, 1)}`,
		navBarHoverFocus: `${rgba(starWarsBlue, 0.55)}`,
		navBarHoverFocusAction: "none",
		sliderArrow: `${fontColor}`,
		sliderArrowActive: `${fontColor}`,
		sliderArrowOpacity: "1",
		sliderArrowSecondary: `${fontColor}`,
		sliderBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleActive: `${fontColor}`,
		sliderCircleBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleBorder: `${rgba(fontColor, 0.2)}`,
		sliderCircleHoverFocus: `${rgba(fontColor, 0.2)}`,
		sliderCircleOpacity: `1`,
		sliderLine: `linear-gradient(to right, transparent 50%, ${fontColor} 50%)`,
		sliderLinePortrait: `linear-gradient(to bottom, transparent 50%, ${fontColor} 50%)`,
		tabHeadingsBorder: `1px solid ${rgba(fontColor, 0.2)}`,
		tabHeadingsBorderActive: `0`,
		tabHeadingsBorderBottomActive: `2px solid ${fontColor}`,
		tabHeadingsBorderRadius: `0`,
		tabHeadingsColor: `${rgba(fontColor, 1)}`,
		tabHeadingsColorActive: `${fontColor}`,
		tabHeadingsColorHoverFocus: `${fontColor}`,
		tabHeadingsJustifyContent: `space-between`
	};
};

export const themeNineties = () => {
	const bgColor = "#ffffff";
	const fontColor = "#000000";
	const starWarsBlue = "#000000";
	return {
		appBg: `url(${totallyNinetiesBgImage})`,
		appBgAnimation: `${bgColor}`,
		appBgColor: `${bgColor}`,
		appBgMobile: `url(${totallyNinetiesBgImage})`,
		appfontFamily: `${timesNewRomanFont}`,
		appfontFamilySecondary: `${comicSansFont}`,
		appfontFamilyTertiary: `${comicSansFont}`,
		bgColor: `${bgColor}`,
		bgColorContent: `${rgba(fontColor, 0.2)}`,
		bgColorOverlay: `${rgba(readableColor(fontColor), 0.01)}`,
		bgColorSecondary: `${bgColor}`,
		borderThin: `1mm ridge gray`,
		buttonBackground: `#e6e6e6`,
		buttonBackgroundHoverFocus: `#e8e8e8`,
		buttonBorder: `1.5mm ridge gray`,
		buttonBorderFocus: `1.5mm ridge black`,
		buttonBorderActive: `1.5mm ridge black`,
		buttonColor: `${rgba(fontColor, 1)}`,
		buttonColorHoverFocus: `${fontColor}`,
		buttonFontWeight: `700`,
		buttonLineHeight: ` 1.2`,
		buttonSpanDisplay: `block`,
		buttonTextTransform: `uppercase`,
		colorLight: `${lighten(0.42, fontColor)}`,
		colorSlightOpacity: `${rgba(fontColor, 0.56)}`,
		CTAColor: `${rgba(starWarsBlue, 1)}`,
		CTAColorSecondary: `${rgba(starWarsBlue, 1)}`,
		CTAUnderline: `none`,
		fontColor: `${fontColor}`,
		fontColorOpposite: `${readableColor(fontColor)}`,
		fontColorSecondary: `${fontColor}`,
		fontSelection: `${invert(fontColor)}`,
		fullScreenHoldBg: ` linear-gradient( ${invert(bgColor)}, ${invert(
			bgColor
		)})`,
		logoBgColor: `${rgba(fontColor, 1)}`,
		logoBgHoverColor: `${fontColor}`,
		logoBorderBottom: `1px solid ${rgba(fontColor, 1)}`,
		logoBorderRadius: `0`,
		logoInnerFillColor: `${starWarsBlue}`,
		logoInnerFillColorHoverFocus: `${starWarsBlue}`,
		logoOuterFillColor: `${starWarsBlue}`,
		modalFullScreenBg: `${bgColor}`,
		modalFullScreenBgColor: `transparent`,
		modalFullScreenBgMobile: `${bgColor}`,
		navBarBg: "transparent",
		navBarBgComplement: `${bgColor}`,
		navBarBorder: `1mm ridge gray`,
		navBarButtonColor: `${starWarsBlue}`,
		navBarButtonActive: `${rgba(starWarsBlue, 0.55)}`,
		navBarButtonComplementaryHoverText: `${rgba(fontColor, 0.55)}`,
		navBarButtonComplementaryText: `${rgba(fontColor, 1)}`,
		navBarHoverFocus: `${rgba(starWarsBlue, 0.55)}`,
		navBarHoverFocusAction: "none",
		sliderArrow: `${fontColor}`,
		sliderArrowActive: `${fontColor}`,
		sliderArrowOpacity: "1",
		sliderArrowSecondary: `${fontColor}`,
		sliderBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleActive: `${fontColor}`,
		sliderCircleBg: `${rgba(fontColor, 0.2)}`,
		sliderCircleBorder: `${rgba(fontColor, 0.2)}`,
		sliderCircleHoverFocus: `${rgba(fontColor, 0.2)}`,
		sliderCircleOpacity: `1`,
		sliderLine: `linear-gradient(to right, transparent 50%, ${fontColor} 50%)`,
		sliderLinePortrait: `linear-gradient(to bottom, transparent 50%, ${fontColor} 50%)`,
		tabHeadingsBorder: `1mm ridge gray`,
		tabHeadingsBorderActive: `0`,
		tabHeadingsBorderBottomActive: `1mm ridge gray`,
		tabHeadingsBorderRadius: `0`,
		tabHeadingsColor: `${rgba(fontColor, 1)}`,
		tabHeadingsColorActive: `${fontColor}`,
		tabHeadingsColorHoverFocus: `${fontColor}`,
		tabHeadingsJustifyContent: `space-between`
	};
};
