import videosofmeaptDancingLocal from "./media/appVideos/videosofmeaptDancing.mp4";
import videosOfMeHerbieDuahCom from "./media/appVideos/videosOfMeHerbieDuahCom.mp4";
import startNowresumeEmailLocal from "./media/appVideos/startNowresumeEmail.mp4";
import ugggiftguideLocal from "./media/appVideos/ugggiftguide.mp4";
import uggPhillipLimLocal from "./media/appVideos/uggPhillipLim.mp4";
import videosofmecarribeanQueenLocal from "./media/appVideos/videosofmecarribeanQueen.mp4";
import videosofmetoastSquadLocal from "./media/appVideos/videosofmetoastSquad.mp4";
import startNowcoverLetterGifLocal from "./media/appVideos/startNowcoverLetterGif.mp4";
import thisAppGatsbyLocal from "./media/appVideos/thisAppGatsby.mp4";
import thisAppherokuappdesktopLocal from "./media/appVideos/thisAppherokuappdesktop.mp4";
import uggJeremyScottDesktopLocal from "./media/appVideos/uggJeremyScottDesktop.mp4";
import uggslidesemailLocal from "./media/appVideos/uggslidesemail.mp4";
import uggshoeuggemailLocal from "./media/appVideos/uggshoeuggemail.mp4";
import videosofme404Local from "./media/appVideos/videosofme404.mp4";
import videosofmedadDanceLocal from "./media/appVideos/videosofmedadDance.mp4";
import videosofmegood404SnowLocal from "./media/appVideos/videosofmegood404Snow.mp4";
import videosofmemillyRockByPoolLocal from "./media/appVideos/videosofmemillyRockByPool.mp4";
import videosofmemillyrockgrandcanyonLocal from "./media/appVideos/videosofmemillyrockgrandcanyon.mp4";
import videosofmeoffRoadingDrivingLocal from "./media/appVideos/videosofmeoffRoadingDriving.mp4";
import videosofmeOffRoadSplashLocal from "./media/appVideos/videosofmeOffRoadSplash.mp4";
import videosofmeoffRoadStuckLocal from "./media/appVideos/videosofmeoffRoadStuck.mp4";
import videosofmephotosSedonaLocal from "./media/appVideos/videosofmephotosSedona.mp4";
import videosofmeraveMillyRockLocal from "./media/appVideos/videosofmeraveMillyRock.mp4";
import videosofmesoreLoserLocal from "./media/appVideos/videosofmesoreLoser.mp4";
import videosofmeStandUpLocal from "./media/appVideos/videosofmeStandUp.mp4";
import videosofmetoast_1Local from "./media/appVideos/videosofmetoast_1.mp4";
import videosofmevNeckCrewNeckLocal from "./media/appVideos/videosofmevNeckCrewNeck.mp4";
import videosofmewakandaLocal from "./media/appVideos/videosofmewakanda.mp4";
import videosofmehammockChilling_1Local from "./media/appVideos/videosofmehammockChilling_1.mp4";
import SliderUIMobileLocal from "./media/appVideos/SliderUIMobile.mp4";
import SliderUIDesktopLocal from "./media/appVideos/SliderUIDesktop.mp4";

import eightFortySixmobileLocal from "./media/appVideos/eightFortySixmobile.mp4";
import eightFortySixdesktopLocal from "./media/appVideos/eightFortySixdesktop.mp4";
import eightFortySixdesktop2Local from "./media/appVideos/eightFortySixdesktop2.mp4";

export const eightFortySixmobileVid = ["eightFortySixmobile_bjaf2r", eightFortySixmobileLocal];
export const eightFortySixdesktop = ["eightFortySixdesktop_w7egt8", eightFortySixdesktopLocal];
export const eightFortySixdesktop2 = ["eightFortySixdesktop2_jvxnfp", eightFortySixdesktop2Local];
export const SliderUIMobile = ["SliderUIMobile_kxrjaa", SliderUIMobileLocal];
export const SliderUIDesktop = ["SliderUIDesktop_rxwbmr", SliderUIDesktopLocal];
export const uggPhillipLim = ["uggPhillipLim_pem01g", uggPhillipLimLocal];
export const videosofmecarribeanQueen = ["videosofmecarribeanQueen_i8wj6f", videosofmecarribeanQueenLocal];
export const videosofmetoastSquad = ["videosofmetoastSquad_mas3ck", videosofmetoastSquadLocal];
export const startNowcoverLetterGif = ["startNowcoverLetterGif_bvccsc", startNowcoverLetterGifLocal];
export const thisAppGatsby = ["thisAppGatsby_t82wvg", thisAppGatsbyLocal];
export const thisAppherokuappdesktop = ["thisAppherokuappdesktop_sditja", thisAppherokuappdesktopLocal];
export const uggJeremyScottDesktop = ["uggJeremyScottDesktop_sgvscy", uggJeremyScottDesktopLocal];
export const uggslidesemail = ["uggslidesemail_ksnfol", uggslidesemailLocal];
export const videosofme404 = ["videosofme404_rdozpg", videosofme404Local];
export const videosofmedadDance = ["videosofmedadDance_zo2r8z", videosofmedadDanceLocal];
export const videosofmegood404Snow = ["videosofmegood404Snow_mk6luq", videosofmegood404SnowLocal];
export const videosofmemillyRockByPool = ["videosofmemillyRockByPool_a7p87u", videosofmemillyRockByPoolLocal];
export const videosofmemillyrockgrandcanyon = [
  "videosofmemillyrockgrandcanyon_wtkrcp",
  videosofmemillyrockgrandcanyonLocal,
];
export const videosofmeoffRoadingDriving = ["videosofmeoffRoadingDriving_cotere", videosofmeoffRoadingDrivingLocal];
export const videosofmeOffRoadSplash = ["videosofmeOffRoadSplash_wgv7ye", videosofmeOffRoadSplashLocal];
export const videosofmeoffRoadStuck = ["videosofmeoffRoadStuck_qrloha", videosofmeoffRoadStuckLocal];
export const videosofmephotosSedona = ["videosofmephotosSedona_ryjt9j", videosofmephotosSedonaLocal];
export const videosofmeraveMillyRock = ["videosofmeraveMillyRock_ru8zvg", videosofmeraveMillyRockLocal];
export const videosofmesoreLoser = ["videosofmesoreLoser_lpbxzg", videosofmesoreLoserLocal];
export const videosofmeStandUp = ["videosofmeStandUp_qown9l", videosofmeStandUpLocal];
export const videosofmetoast_1 = ["videosofmetoast_1_ald4hk", videosofmetoast_1Local];
export const videosofmevNeckCrewNeck = ["videosofmevNeckCrewNeck_wkqon3", videosofmevNeckCrewNeckLocal];
export const videosofmewakanda = ["videosofmewakanda_jabpvw", videosofmewakandaLocal];
export const videosofmehammockChilling_1 = ["videosofmehammockChilling_1_y3juyj", videosofmehammockChilling_1Local];
export const videosofmeaptDancing = ["videosofmeaptDancing_bkn88u", videosofmeaptDancingLocal];
export const videosOfMeHerbieDuahComl = ["startNowHerbieDuahCom_rryanb", videosOfMeHerbieDuahCom];
export const startNowresumeEmail = ["startNowresumeEmail_czqk7z", startNowresumeEmailLocal];
export const uggshoeuggemail = ["uggshoeuggemail_ptamto", uggshoeuggemailLocal];
export const ugggiftguide = ["ugggiftguide_nbixlt", ugggiftguideLocal];
